#!/bin/bash
# TODO wait for 6am?

if [ ! -f input ]
then
  wget https://adventofcode.com/`date +%Y`/day/`date +%d | sed s/^0//`/input --header="Cookie: session=$AOC_SESS_ID" -O input
fi

runscript() {
  clear
  date
  time ruby ./a0.rb
}

runscript

inotifywait -q -m -e close_write a0.rb |
while read -r filename event; do
  runscript
done
